### ISSUE TITLE
FalseJS

### ISSUE THREAD

**Issue by tj-commits** [mde/false#15]
Hello there, I have created a library called [FalseJS](https://github.com/tj-commits/falsejs) which works similarly to this library to return false. It depends on this package, and I would like some feedback on my library. Thank you

**Comment by mde** [comment]
This looks incredibly well written and useful. I'm sure you'll get feedback from the community that it might be better written with some sort of type system in mind. I'll be happy to promote this library at every possible opportunity. Excellent work!

**Comment by tj-commits** [comment]
Thanks

**Comment by tj-commits** [comment]
By type system, what do you mean? Should I rewrite in TypeScript
